### ISSUE TITLE
CUSPARSE API failed

### ISSUE THREAD

**Issue by zzzlxhhh** [AlibabaResearch/flash-llm#11]
Thanks for your excellent work!
However, when running kernel benchmarks, it reports:
```
Launching CuBlas...
Launching Flash-LLM...
Launching Flash-LLM without Ahead of Time Sparse Data Reordering...
Launching CuSparse_ColMajor...
Launching CuSparse_RowMajor...
Launching Sputnik...
Launching sparTA...
NZ_A: 0.300      NZ_A1: 0.277    NZ_A2: 0.023
CUSPARSE API failed at line 130 with error: internal error (7)
```
The API seems to fail at line 130 of `sparTA.h`:
```
CHECK_CUSPARSE(cusparseLtMatmulAlgSelectionInit(&handle, &alg_sel, &matmul, CUSPARSELT_MATMUL_ALG_DEFAULT))
```
So far, I do not have any ideas to solve this problem. Could you please give some insights about this problem?

**Comment by zzzlxhhh** [comment]
And, could you specify your CUSPARSELT version?

**Comment by Guanchen11** [comment]
Hi, did you solved this issue? I met the same problem

**Comment by simlaharma** [comment]
Hello, I have the same problem. @zzzlxhhh @Guanchen11 did any one you solve this issue?

**Comment by mohamedaminebentayeb** [comment]
Hello, I have the same problem. @zzzlxhhh @Guanchen11 @simlaharma, did any of you solve this issue?
